before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  -
    env:
      - CGO_ENABLED=0

    binary: main
    
    flags:
      - -trimpath #removes all file system paths from the compiled executable

    goos:
      - linux
      - windows
      - darwin

    goarch:
      - amd64
      - arm64

archives:
  -
    replacements:
      darwin: macOs
      linux: linux
      windows: windows
      amd64: 64-bit
      arm64: arm64-bit

    format: tar.gz

    files:
      - none*

    format_overrides:
      - goos: windows
        format: zip


checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ .ProjectName }}_v{{ .Version }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: ErwinsExpertise
    name: gha-auto-release